<?php

namespace TestBundle\Repository;

/**
 * carRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carRepository extends \Doctrine\ORM\EntityRepository
{
}
